apiVersion: v1
kind: Service
metadata:
  name: jenkins-demo-service
spec:
  type: NodePort
  selector:
    app: jenkins-demo
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
